-- require("cyberdream").setup({
--     -- Recommended - see "Configuring" below for more config options
--     transparent = true,
--     italic_comments = true,
--     hide_fillchars = false,
--     borderless_telescope = true,
-- })
